version: "3.3"
services:
  vault:
    image: vault
    ports:
      - '8200:8200'
    restart: always
    environment:
      - 'VAULT_ADDR=http://localhost:8200'
      - 'VAULT_DEV_ROOT_TOKEN_ID=00000000-0000-0000-0000-000000000000'
      - 'dev'
    cap_add:
      - IPC_LOCK
  db:
    image: postgres:alipine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'